# Generated by Django 4.1.1 on 2022-10-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
